server.port: 8888
spring:
    jpa.hibernate.ddl-auto: update
    datasource.url: jdbc:mysql://localhost:3306/student_db
    datasource.username: root
    datasource.password: mysql
security: 
  oauth2:
    client:
      clientId: 267018313777934
      clientSecret: 9326a4dcc6852074f09d4fccadea1bdd
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
      
